name: try-jupyter
channels:
- conda-forge
dependencies:
- python =3.12
- mamba
- pydata-sphinx-theme
- myst-parser
- bqplot
- ipycanvas >=0.9.1
- ipyleaflet
- ipympl >=0.8.2
- ipywidgets >=8.1.7,<9
- jupyterlab >=4.4.3,<=4.5
- jupyterlab-language-pack-fr-FR
- jupyterlab-language-pack-zh-CN
- jupyterlab-fasta >=3.3.0,<4
- jupyterlab-geojson >=3.4.0,<4
- jupyterlab-tour
- jupyterlab-night
- jupyterlite-core =0.6.0
- jupyterlite-pyodide-kernel =0.6.0
- jupyterlite-sphinx >=0.20.2,<0.21
- jupyterlite-terminal >=0.2.1,<0.3.0
- jupyterlite-xeus>=4.0.0
- notebook >=7.4.3,<7.5
- pip
- plotly >=6,<7
# micromamba and nodejs are needed for jupyterlite-terminal
- micromamba >=2.0.5,<3
- nodejs =22
- pip:
  - jupyterlite-xeus-sqlite==0.2.1
  - jupyterlab-open-url-parameter >=0.3.0
